site_name: PUEBI Daring
pages:
  - 'Beranda': 'index.md'
  - 'Pemakaian Huruf':
    - 'Tinjauan': 'huruf/index.md'
    - 'Huruf Abjad': 'huruf/huruf-abjad.md'
    - 'Huruf Vokal': 'huruf/huruf-vokal.md'
    - 'Huruf Konsonan': 'huruf/huruf-konsonan.md'
    - 'Huruf Diftong': 'huruf/huruf-diftong.md'
    - 'Gabungan Huruf Konsonan': 'huruf/gabungan-huruf-konsonan.md'
    - 'Huruf Kapital': 'huruf/huruf-kapital.md'
    - 'Huruf Miring': 'huruf/huruf-miring.md'
    - 'Huruf Tebal': 'huruf/huruf-tebal.md'
  - 'Penulisan Kata':
    - 'Tinjauan': 'kata/index.md'
    - 'Kata Dasar': 'kata/kata-dasar.md'
    - 'Kata Berimbuhan': 'kata/kata-berimbuhan.md'
    - 'Bentuk Ulang': 'kata/bentuk-ulang.md'
    - 'Gabungan Kata': 'kata/gabungan-kata.md'
    - 'Pemenggalan Kata': 'kata/pemenggalan-kata.md'
    - 'Kata Depan': 'kata/kata-depan.md'
    - 'Partikel': 'kata/partikel.md'
    - 'Singkatan dan Akronim': 'kata/singkatan-dan-akronim.md'
    - 'Angka dan Bilangan': 'kata/angka-dan-bilangan.md'
    - 'Kata Ganti': 'kata/kata-ganti.md'
    - 'Kata Sandang': 'kata/kata-sandang.md'
  - 'Pemakaian Tanda Baca':
    - 'Tinjauan': 'tanda-baca/index.md'
    - 'Tanda Titik (.)': 'tanda-baca/tanda-titik.md'
    - 'Tanda Koma (,)': 'tanda-baca/tanda-koma.md'
    - 'Tanda Titik Koma (;)': 'tanda-baca/tanda-titik-koma.md'
    - 'Tanda Titik Dua (:)': 'tanda-baca/tanda-titik-dua.md'
    - 'Tanda Hubung (-)': 'tanda-baca/tanda-hubung.md'
    - 'Tanda Pisah (—)': 'tanda-baca/tanda-pisah.md'
    - 'Tanda Tanya (?)': 'tanda-baca/tanda-tanya.md'
    - 'Tanda Seru (!)': 'tanda-baca/tanda-seru.md'
    - 'Tanda Elipsis (…)': 'tanda-baca/tanda-elipsis.md'
    - 'Tanda Petik ("…")': 'tanda-baca/tanda-petik.md'
    - 'Tanda Petik Tunggal (''…'')': 'tanda-baca/tanda-petik-tunggal.md'
    - 'Tanda Kurung ((…))': 'tanda-baca/tanda-kurung.md'
    - 'Tanda Kurung Siku ([…])': 'tanda-baca/tanda-kurung-siku.md'
    - 'Tanda Garis Miring (/)': 'tanda-baca/tanda-garis-miring.md'
    - 'Tanda Penyingkat ('')': 'tanda-baca/tanda-penyingkat-apostrof.md'
  - 'Penulisan Unsur Serapan': 'unsur-serapan/index.md'
theme: 'readthedocs'
repo_name: 'GitHub'
repo_url: 'https://github.com/ivanlanin/puebi'
google_analytics: ['UA-80210173-1', 'auto']
markdown_extensions:
  - admonition